# Generated by Django 5.0 on 2024-03-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0019_alter_salerdetail_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerdetail',
            name='alternate_mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
