# Generated by Django 5.0 on 2024-03-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0020_alter_salerdetail_alternate_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerdetail',
            name='mobile',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
