# Generated by Django 5.0 on 2024-02-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cart_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='state',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Mymensingh', 'Mymensingh'), ('Barishal', 'Barishal'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Noakhali', 'Noakhali'), ('Rangpur', 'Rangpur')], max_length=50, null=True),
        ),
    ]
